# CBT Configuration for Example Environment
# This single configuration file is used by all components in the docker-compose setup

# Logging level
logging: debug

# Metrics server address
metricsAddr: ":9090"

# Health check server address
healthCheckAddr: ":8080"

# Optional pprof profiling
# pprofAddr: ":6060"

# API server configuration
api:
  enabled: true
  addr: ":8888"  # API listens on port 8888

# ClickHouse configuration (used by all components)
clickhouse:
  url: "http://clickhouse:8123"
  cluster: ""
  localSuffix: "_local"
  queryTimeout: 300s  # Increased from 30s to handle large queries
  insertTimeout: 5m    # Increased from 60s for bulk operations
  debug: false
  keepAlive: 30s
  # Admin tables configuration for each transformation type
  admin:
    incremental:
      database: admin
      table: cbt_incremental
    scheduled:
      database: admin
      table: cbt_scheduled

# Redis configuration (used by coordinator, worker, and rerun command)
redis:
  url: "redis://redis:6379"

# Scheduler settings
scheduler:
  concurrency: 10
  consolidation: "@every 10m"

# Worker-specific settings (ignored by coordinator and CLI)
worker:
  concurrency: 10
  # No model tag filtering in example
  # modelTags:
  #   include: []
  #   exclude: []
  #   require: []
  shutdownTimeout: 30

# Model configuration with optional default databases
models:
  external:
    paths:
      - "/app/models/external"
    defaultDatabase: "ethereum"  # Default database for external models
  transformations:
    paths:
      - "/app/models/transformations"
    defaultDatabase: "analytics"  # Default database for transformation models
    # Optional: Global custom environment variables for all transformations
    env:
      API_KEY: "global_api_key_12345"
      ENVIRONMENT: "development"

# Optional: Override configuration for specific transformation models
# Useful for environment-specific adjustments (staging, production, etc.)
# You can use either full ID (database.table) or table-only format for models using default database
# overrides:
#   # Disable a model entirely (full ID format)
#   analytics.block_never_loads:
#     enabled: false
#   
#   # Override using table-only format (works because model uses defaultDatabase: "analytics")
#   hourly_block_stats:
#     config:
#       interval:
#         max: 7200  # Increase to 2 hours in staging
#       schedules:
#         forwardfill: "@every 10m"  # Slower schedule
#         backfill: ""  # Disable backfill (use empty string)
#   
#   # Table-only format for simpler configs
#   entity_changes:
#     config:
#       schedules:
#         forwardfill: "@every 5m"
#         backfill: "@every 30m"
#   
#   # Mix both formats as needed
#   five_minute_report:  # Table-only format
#     config:
#       tags:
#         - "staging-only"
#         - "low-priority"
#   
#   # Models with custom databases must use full ID
#   custom_db.special_model:
#     config:
#       limits:
#         min: 1000000  # Start from specific position
#         max: 2000000  # End at specific position