# CBT Configuration for Example Environment
# This single configuration file is used by all components in the docker-compose setup

# Logging level
logging: debug

# Metrics server address
metricsAddr: ":9090"

# Health check server address
healthCheckAddr: ":8083"

# Optional pprof profiling
# pprofAddr: ":6060"

# Frontend service configuration (includes API)
# The frontend serves both the web UI and API endpoints on the same port
# API endpoints are available at /api/v1/*
frontend:
  enabled: true
  addr: ":8080"  # Frontend and API listen on port 8080

# ClickHouse configuration (used by all components)
clickhouse:
  url: "http://clickhouse:8123"
  cluster: ""
  localSuffix: "_local"
  queryTimeout: 300s  # Increased from 30s to handle large queries
  insertTimeout: 5m    # Increased from 60s for bulk operations
  debug: false
  keepAlive: 30s
  # Admin tables configuration for each transformation type
  admin:
    incremental:
      database: admin
      table: cbt_incremental
    scheduled:
      database: admin
      table: cbt_scheduled

# Redis configuration (used by coordinator, worker, and rerun command)
redis:
  url: "redis://redis:6379"

# Scheduler settings
scheduler:
  concurrency: 10
  consolidation: "@every 10m"

# Worker-specific settings (ignored by coordinator and CLI)
worker:
  concurrency: 10
  # No model tag filtering in example
  # modelTags:
  #   include: []
  #   exclude: []
  #   require: []
  shutdownTimeout: 30

# Model configuration with optional default databases
models:
  external:
    paths:
      - "/app/models/external"
    defaultDatabase: "ethereum"  # Default database for external models
  transformations:
    paths:
      - "/app/models/transformations"
    defaultDatabase: "analytics"  # Default database for transformation models
    # Optional: Global custom environment variables for all transformations
    env:
      API_KEY: "global_api_key_12345"
      ENVIRONMENT: "development"

  # Optional: Override configuration for specific transformation models
  # Useful for environment-specific adjustments (staging, production, etc.)
  # You can use either full ID (database.table) or table-only format for models using default database
  # Overrides apply different fields based on transformation type (incremental vs scheduled)
  overrides:
    # SCHEDULED TRANSFORMATION OVERRIDE TEST
    # Override exchange_rates to run every 2 minutes instead of every 30 seconds
    reference.exchange_rates:
      config:
        schedule: "@every 2m"  # Override the cron schedule
        tags:
          - "override-test"

    # Override system_health using full ID format
    monitoring.system_health_check:
      config:
        schedule: "@every 5m"  # Override from @every 1m to @every 5m
        tags:
          - "monitoring-override"
interval_types:
  slot:
  - name: Slot
    expression: "math.floor((value - 1606824023) / 12)"
  - name: Datetime
    format: datetime
    expression: "value * 1000"
  - name: Timestamp
  block:
  - name: Block number