# CBT Configuration for Example Environment
# This single configuration file is used by all components in the docker-compose setup

# Logging level
logging: debug

# Metrics server address
metricsAddr: ":9090"

# Health check server address
healthCheckAddr: ":8080"

# Optional pprof profiling
# pprofAddr: ":6060"

# ClickHouse configuration (used by all components)
clickhouse:
  url: "http://clickhouse:8123"
  cluster: ""
  localSuffix: "_local"
  queryTimeout: 300s  # Increased from 30s to handle large queries
  insertTimeout: 5m    # Increased from 60s for bulk operations
  debug: false
  keepAlive: 30s
  # Admin tables configuration for each transformation type
  admin:
    incremental:
      database: admin
      table: cbt_incremental
    scheduled:
      database: admin
      table: cbt_scheduled

# Redis configuration (used by coordinator, worker, and rerun command)
redis:
  url: "redis://redis:6379"

# Scheduler settings
scheduler:
  concurrency: 10
  consolidation: "@every 10m"

# Worker-specific settings (ignored by coordinator and CLI)
worker:
  concurrency: 10
  # No model tag filtering in example
  # modelTags:
  #   include: []
  #   exclude: []
  #   require: []
  shutdownTimeout: 30

# Model configuration with optional default databases
models:
  external:
    paths:
      - "/app/models/external"
    defaultDatabase: "ethereum"  # Default database for external models
  transformations:
    paths:
      - "/app/models/transformations"
    defaultDatabase: "analytics"  # Default database for transformation models