logging: "info" # panic,fatal,warn,info,debug,trace
metricsAddr: ":9090"
# healthCheckAddr: ":9191" # optional. if supplied it enables healthcheck server
# pprofAddr: ":6060" # optional. if supplied it enables pprof server

# Redis configuration for distributed task queues and leader election
redis:
  address: "redis://localhost:6379"
  prefix: "cbt"

# Clickhouse configuration
clickhouse:
  url: "http://localhost:8123/default"
