// Code generated by MockGen. DO NOT EDIT.
// Source: tracker.go
//
// Generated by this command:
//
//	mockgen -package mock -destination mock/tracker.mock.go -source tracker.go scheduleTracker
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockscheduleTracker is a mock of scheduleTracker interface.
type MockscheduleTracker struct {
	ctrl     *gomock.Controller
	recorder *MockscheduleTrackerMockRecorder
	isgomock struct{}
}

// MockscheduleTrackerMockRecorder is the mock recorder for MockscheduleTracker.
type MockscheduleTrackerMockRecorder struct {
	mock *MockscheduleTracker
}

// NewMockscheduleTracker creates a new mock instance.
func NewMockscheduleTracker(ctrl *gomock.Controller) *MockscheduleTracker {
	mock := &MockscheduleTracker{ctrl: ctrl}
	mock.recorder = &MockscheduleTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscheduleTracker) EXPECT() *MockscheduleTrackerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockscheduleTracker) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockscheduleTrackerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockscheduleTracker)(nil).Close))
}

// DeleteLastRun mocks base method.
func (m *MockscheduleTracker) DeleteLastRun(ctx context.Context, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLastRun", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLastRun indicates an expected call of DeleteLastRun.
func (mr *MockscheduleTrackerMockRecorder) DeleteLastRun(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLastRun", reflect.TypeOf((*MockscheduleTracker)(nil).DeleteLastRun), ctx, taskID)
}

// GetAllTaskIDs mocks base method.
func (m *MockscheduleTracker) GetAllTaskIDs(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTaskIDs", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTaskIDs indicates an expected call of GetAllTaskIDs.
func (mr *MockscheduleTrackerMockRecorder) GetAllTaskIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTaskIDs", reflect.TypeOf((*MockscheduleTracker)(nil).GetAllTaskIDs), ctx)
}

// GetLastRun mocks base method.
func (m *MockscheduleTracker) GetLastRun(ctx context.Context, taskID string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastRun", ctx, taskID)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastRun indicates an expected call of GetLastRun.
func (mr *MockscheduleTrackerMockRecorder) GetLastRun(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastRun", reflect.TypeOf((*MockscheduleTracker)(nil).GetLastRun), ctx, taskID)
}

// SetLastRun mocks base method.
func (m *MockscheduleTracker) SetLastRun(ctx context.Context, taskID string, timestamp time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastRun", ctx, taskID, timestamp)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLastRun indicates an expected call of SetLastRun.
func (mr *MockscheduleTrackerMockRecorder) SetLastRun(ctx, taskID, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastRun", reflect.TypeOf((*MockscheduleTracker)(nil).SetLastRun), ctx, taskID, timestamp)
}
