// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zModelDetail = z.object({
  id: z.string(),
  type: z.string(),
  database: z.string(),
  table: z.string(),
  config: z.record(z.string(), z.unknown()),
  dependencies: z.optional(z.array(z.string())),
  dependents: z.optional(z.array(z.string())),
});

export const zModelsResponse = z.object({
  models: z.array(zModelDetail),
  total: z.int(),
});

export const zError = z.object({
  error: z.string(),
  code: z.int(),
});

export const zGetModelsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      type: z.optional(z.enum(['transformation', 'external'])),
      database: z.optional(z.string()),
    })
  ),
});

/**
 * List of models
 */
export const zGetModelsResponse = zModelsResponse;

export const zGetModelByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    model_id: z.string(),
  }),
  query: z.optional(z.never()),
});

/**
 * Model details
 */
export const zGetModelByIdResponse = zModelDetail;
