name: 'Go Setup'
description: 'Sets up Go environment with caching'

inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.26.0'

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version: ${{ inputs.go-version }}
        cache: true
