// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:8080/api/v1' | (string & {});
};

export type ModelsResponse = {
  models: Array<ModelDetail>;
  total: number;
};

export type ModelDetail = {
  id: string;
  type: string;
  database: string;
  table: string;
  config: {
    [key: string]: unknown;
  };
  dependencies?: Array<string>;
  dependents?: Array<string>;
};

export type _Error = {
  error: string;
  code: number;
};

export type GetModelsData = {
  body?: never;
  path?: never;
  query?: {
    type?: 'transformation' | 'external';
    database?: string;
  };
  url: '/models';
};

export type GetModelsResponses = {
  /**
   * List of models
   */
  200: ModelsResponse;
};

export type GetModelsResponse = GetModelsResponses[keyof GetModelsResponses];

export type GetModelByIdData = {
  body?: never;
  path: {
    model_id: string;
  };
  query?: never;
  url: '/models/{model_id}';
};

export type GetModelByIdErrors = {
  /**
   * Resource not found
   */
  404: _Error;
};

export type GetModelByIdError = GetModelByIdErrors[keyof GetModelByIdErrors];

export type GetModelByIdResponses = {
  /**
   * Model details
   */
  200: ModelDetail;
};

export type GetModelByIdResponse = GetModelByIdResponses[keyof GetModelByIdResponses];
