// Code generated by MockGen. DO NOT EDIT.
// Source: dag.go
//
// Generated by this command:
//
//	mockgen -package mock -destination mock/dag.mock.go -source dag.go DAGReader
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	models "github.com/ethpandaops/cbt/pkg/models"
	transformation "github.com/ethpandaops/cbt/pkg/models/transformation"
	gomock "go.uber.org/mock/gomock"
)

// MockDAGReader is a mock of DAGReader interface.
type MockDAGReader struct {
	ctrl     *gomock.Controller
	recorder *MockDAGReaderMockRecorder
	isgomock struct{}
}

// MockDAGReaderMockRecorder is the mock recorder for MockDAGReader.
type MockDAGReaderMockRecorder struct {
	mock *MockDAGReader
}

// NewMockDAGReader creates a new mock instance.
func NewMockDAGReader(ctrl *gomock.Controller) *MockDAGReader {
	mock := &MockDAGReader{ctrl: ctrl}
	mock.recorder = &MockDAGReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDAGReader) EXPECT() *MockDAGReaderMockRecorder {
	return m.recorder
}

// GetAllDependencies mocks base method.
func (m *MockDAGReader) GetAllDependencies(id string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDependencies", id)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAllDependencies indicates an expected call of GetAllDependencies.
func (mr *MockDAGReaderMockRecorder) GetAllDependencies(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDependencies", reflect.TypeOf((*MockDAGReader)(nil).GetAllDependencies), id)
}

// GetAllDependents mocks base method.
func (m *MockDAGReader) GetAllDependents(id string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDependents", id)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAllDependents indicates an expected call of GetAllDependents.
func (mr *MockDAGReaderMockRecorder) GetAllDependents(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDependents", reflect.TypeOf((*MockDAGReader)(nil).GetAllDependents), id)
}

// GetDependencies mocks base method.
func (m *MockDAGReader) GetDependencies(id string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDependencies", id)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetDependencies indicates an expected call of GetDependencies.
func (mr *MockDAGReaderMockRecorder) GetDependencies(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDependencies", reflect.TypeOf((*MockDAGReader)(nil).GetDependencies), id)
}

// GetDependents mocks base method.
func (m *MockDAGReader) GetDependents(id string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDependents", id)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetDependents indicates an expected call of GetDependents.
func (mr *MockDAGReaderMockRecorder) GetDependents(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDependents", reflect.TypeOf((*MockDAGReader)(nil).GetDependents), id)
}

// GetExternalNode mocks base method.
func (m *MockDAGReader) GetExternalNode(id string) (models.External, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalNode", id)
	ret0, _ := ret[0].(models.External)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExternalNode indicates an expected call of GetExternalNode.
func (mr *MockDAGReaderMockRecorder) GetExternalNode(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalNode", reflect.TypeOf((*MockDAGReader)(nil).GetExternalNode), id)
}

// GetExternalNodes mocks base method.
func (m *MockDAGReader) GetExternalNodes() []models.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalNodes")
	ret0, _ := ret[0].([]models.Node)
	return ret0
}

// GetExternalNodes indicates an expected call of GetExternalNodes.
func (mr *MockDAGReaderMockRecorder) GetExternalNodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalNodes", reflect.TypeOf((*MockDAGReader)(nil).GetExternalNodes))
}

// GetNode mocks base method.
func (m *MockDAGReader) GetNode(id string) (models.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNode", id)
	ret0, _ := ret[0].(models.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNode indicates an expected call of GetNode.
func (mr *MockDAGReaderMockRecorder) GetNode(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNode", reflect.TypeOf((*MockDAGReader)(nil).GetNode), id)
}

// GetStructuredDependencies mocks base method.
func (m *MockDAGReader) GetStructuredDependencies(id string) []transformation.Dependency {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStructuredDependencies", id)
	ret0, _ := ret[0].([]transformation.Dependency)
	return ret0
}

// GetStructuredDependencies indicates an expected call of GetStructuredDependencies.
func (mr *MockDAGReaderMockRecorder) GetStructuredDependencies(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStructuredDependencies", reflect.TypeOf((*MockDAGReader)(nil).GetStructuredDependencies), id)
}

// GetTransformationNode mocks base method.
func (m *MockDAGReader) GetTransformationNode(id string) (models.Transformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransformationNode", id)
	ret0, _ := ret[0].(models.Transformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransformationNode indicates an expected call of GetTransformationNode.
func (mr *MockDAGReaderMockRecorder) GetTransformationNode(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransformationNode", reflect.TypeOf((*MockDAGReader)(nil).GetTransformationNode), id)
}

// GetTransformationNodes mocks base method.
func (m *MockDAGReader) GetTransformationNodes() []models.Transformation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransformationNodes")
	ret0, _ := ret[0].([]models.Transformation)
	return ret0
}

// GetTransformationNodes indicates an expected call of GetTransformationNodes.
func (mr *MockDAGReaderMockRecorder) GetTransformationNodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransformationNodes", reflect.TypeOf((*MockDAGReader)(nil).GetTransformationNodes))
}

// IsPathBetween mocks base method.
func (m *MockDAGReader) IsPathBetween(from, to string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPathBetween", from, to)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsPathBetween indicates an expected call of IsPathBetween.
func (mr *MockDAGReaderMockRecorder) IsPathBetween(from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPathBetween", reflect.TypeOf((*MockDAGReader)(nil).IsPathBetween), from, to)
}
