// Code generated by MockGen. DO NOT EDIT.
// Source: external.go
//
// Generated by this command:
//
//	mockgen -package mock -destination mock/external.mock.go -source external.go External
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	external "github.com/ethpandaops/cbt/pkg/models/external"
	gomock "go.uber.org/mock/gomock"
)

// MockExternal is a mock of External interface.
type MockExternal struct {
	ctrl     *gomock.Controller
	recorder *MockExternalMockRecorder
	isgomock struct{}
}

// MockExternalMockRecorder is the mock recorder for MockExternal.
type MockExternalMockRecorder struct {
	mock *MockExternal
}

// NewMockExternal creates a new mock instance.
func NewMockExternal(ctrl *gomock.Controller) *MockExternal {
	mock := &MockExternal{ctrl: ctrl}
	mock.recorder = &MockExternalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternal) EXPECT() *MockExternalMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockExternal) GetConfig() external.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig")
	ret0, _ := ret[0].(external.Config)
	return ret0
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockExternalMockRecorder) GetConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockExternal)(nil).GetConfig))
}

// GetConfigMutable mocks base method.
func (m *MockExternal) GetConfigMutable() *external.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigMutable")
	ret0, _ := ret[0].(*external.Config)
	return ret0
}

// GetConfigMutable indicates an expected call of GetConfigMutable.
func (mr *MockExternalMockRecorder) GetConfigMutable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigMutable", reflect.TypeOf((*MockExternal)(nil).GetConfigMutable))
}

// GetID mocks base method.
func (m *MockExternal) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockExternalMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockExternal)(nil).GetID))
}

// GetType mocks base method.
func (m *MockExternal) GetType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockExternalMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockExternal)(nil).GetType))
}

// GetValue mocks base method.
func (m *MockExternal) GetValue() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValue")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetValue indicates an expected call of GetValue.
func (mr *MockExternalMockRecorder) GetValue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockExternal)(nil).GetValue))
}

// SetDefaults mocks base method.
func (m *MockExternal) SetDefaults(defaultCluster, defaultDB string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDefaults", defaultCluster, defaultDB)
}

// SetDefaults indicates an expected call of SetDefaults.
func (mr *MockExternalMockRecorder) SetDefaults(defaultCluster, defaultDB any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaults", reflect.TypeOf((*MockExternal)(nil).SetDefaults), defaultCluster, defaultDB)
}
