// Code generated by MockGen. DO NOT EDIT.
// Source: transformation.go
//
// Generated by this command:
//
//	mockgen -package mock -destination mock/transformation.mock.go -source transformation.go Transformation
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	transformation "github.com/ethpandaops/cbt/pkg/models/transformation"
	gomock "go.uber.org/mock/gomock"
)

// MockTransformation is a mock of Transformation interface.
type MockTransformation struct {
	ctrl     *gomock.Controller
	recorder *MockTransformationMockRecorder
	isgomock struct{}
}

// MockTransformationMockRecorder is the mock recorder for MockTransformation.
type MockTransformationMockRecorder struct {
	mock *MockTransformation
}

// NewMockTransformation creates a new mock instance.
func NewMockTransformation(ctrl *gomock.Controller) *MockTransformation {
	mock := &MockTransformation{ctrl: ctrl}
	mock.recorder = &MockTransformationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransformation) EXPECT() *MockTransformationMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockTransformation) GetConfig() *transformation.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig")
	ret0, _ := ret[0].(*transformation.Config)
	return ret0
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockTransformationMockRecorder) GetConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockTransformation)(nil).GetConfig))
}

// GetHandler mocks base method.
func (m *MockTransformation) GetHandler() transformation.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHandler")
	ret0, _ := ret[0].(transformation.Handler)
	return ret0
}

// GetHandler indicates an expected call of GetHandler.
func (mr *MockTransformationMockRecorder) GetHandler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHandler", reflect.TypeOf((*MockTransformation)(nil).GetHandler))
}

// GetID mocks base method.
func (m *MockTransformation) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockTransformationMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockTransformation)(nil).GetID))
}

// GetType mocks base method.
func (m *MockTransformation) GetType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockTransformationMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockTransformation)(nil).GetType))
}

// GetValue mocks base method.
func (m *MockTransformation) GetValue() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValue")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetValue indicates an expected call of GetValue.
func (mr *MockTransformationMockRecorder) GetValue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockTransformation)(nil).GetValue))
}

// SetDefaultDatabase mocks base method.
func (m *MockTransformation) SetDefaultDatabase(defaultDB string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDefaultDatabase", defaultDB)
}

// SetDefaultDatabase indicates an expected call of SetDefaultDatabase.
func (mr *MockTransformationMockRecorder) SetDefaultDatabase(defaultDB any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultDatabase", reflect.TypeOf((*MockTransformation)(nil).SetDefaultDatabase), defaultDB)
}
