// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -package mock -destination mock/service.mock.go -source service.go Service
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	admin "github.com/ethpandaops/cbt/pkg/admin"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ConsolidateHistoricalData mocks base method.
func (m *MockService) ConsolidateHistoricalData(ctx context.Context, modelID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsolidateHistoricalData", ctx, modelID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsolidateHistoricalData indicates an expected call of ConsolidateHistoricalData.
func (mr *MockServiceMockRecorder) ConsolidateHistoricalData(ctx, modelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsolidateHistoricalData", reflect.TypeOf((*MockService)(nil).ConsolidateHistoricalData), ctx, modelID)
}

// FindGaps mocks base method.
func (m *MockService) FindGaps(ctx context.Context, modelID string, minPos, maxPos, interval uint64) ([]admin.GapInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindGaps", ctx, modelID, minPos, maxPos, interval)
	ret0, _ := ret[0].([]admin.GapInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindGaps indicates an expected call of FindGaps.
func (mr *MockServiceMockRecorder) FindGaps(ctx, modelID, minPos, maxPos, interval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindGaps", reflect.TypeOf((*MockService)(nil).FindGaps), ctx, modelID, minPos, maxPos, interval)
}

// GetCoverage mocks base method.
func (m *MockService) GetCoverage(ctx context.Context, modelID string, startPos, endPos uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoverage", ctx, modelID, startPos, endPos)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoverage indicates an expected call of GetCoverage.
func (mr *MockServiceMockRecorder) GetCoverage(ctx, modelID, startPos, endPos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoverage", reflect.TypeOf((*MockService)(nil).GetCoverage), ctx, modelID, startPos, endPos)
}

// GetExternalBounds mocks base method.
func (m *MockService) GetExternalBounds(ctx context.Context, modelID string) (*admin.BoundsCache, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalBounds", ctx, modelID)
	ret0, _ := ret[0].(*admin.BoundsCache)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExternalBounds indicates an expected call of GetExternalBounds.
func (mr *MockServiceMockRecorder) GetExternalBounds(ctx, modelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalBounds", reflect.TypeOf((*MockService)(nil).GetExternalBounds), ctx, modelID)
}

// GetFirstPosition mocks base method.
func (m *MockService) GetFirstPosition(ctx context.Context, modelID string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstPosition", ctx, modelID)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirstPosition indicates an expected call of GetFirstPosition.
func (mr *MockServiceMockRecorder) GetFirstPosition(ctx, modelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstPosition", reflect.TypeOf((*MockService)(nil).GetFirstPosition), ctx, modelID)
}

// GetIncrementalAdminDatabase mocks base method.
func (m *MockService) GetIncrementalAdminDatabase() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncrementalAdminDatabase")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIncrementalAdminDatabase indicates an expected call of GetIncrementalAdminDatabase.
func (mr *MockServiceMockRecorder) GetIncrementalAdminDatabase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncrementalAdminDatabase", reflect.TypeOf((*MockService)(nil).GetIncrementalAdminDatabase))
}

// GetIncrementalAdminTable mocks base method.
func (m *MockService) GetIncrementalAdminTable() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncrementalAdminTable")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIncrementalAdminTable indicates an expected call of GetIncrementalAdminTable.
func (mr *MockServiceMockRecorder) GetIncrementalAdminTable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncrementalAdminTable", reflect.TypeOf((*MockService)(nil).GetIncrementalAdminTable))
}

// GetLastProcessedPosition mocks base method.
func (m *MockService) GetLastProcessedPosition(ctx context.Context, modelID string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastProcessedPosition", ctx, modelID)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastProcessedPosition indicates an expected call of GetLastProcessedPosition.
func (mr *MockServiceMockRecorder) GetLastProcessedPosition(ctx, modelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastProcessedPosition", reflect.TypeOf((*MockService)(nil).GetLastProcessedPosition), ctx, modelID)
}

// GetLastScheduledExecution mocks base method.
func (m *MockService) GetLastScheduledExecution(ctx context.Context, modelID string) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastScheduledExecution", ctx, modelID)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastScheduledExecution indicates an expected call of GetLastScheduledExecution.
func (mr *MockServiceMockRecorder) GetLastScheduledExecution(ctx, modelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastScheduledExecution", reflect.TypeOf((*MockService)(nil).GetLastScheduledExecution), ctx, modelID)
}

// GetNextUnprocessedPosition mocks base method.
func (m *MockService) GetNextUnprocessedPosition(ctx context.Context, modelID string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextUnprocessedPosition", ctx, modelID)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextUnprocessedPosition indicates an expected call of GetNextUnprocessedPosition.
func (mr *MockServiceMockRecorder) GetNextUnprocessedPosition(ctx, modelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextUnprocessedPosition", reflect.TypeOf((*MockService)(nil).GetNextUnprocessedPosition), ctx, modelID)
}

// GetProcessedRanges mocks base method.
func (m *MockService) GetProcessedRanges(ctx context.Context, modelID string) ([]admin.ProcessedRange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProcessedRanges", ctx, modelID)
	ret0, _ := ret[0].([]admin.ProcessedRange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProcessedRanges indicates an expected call of GetProcessedRanges.
func (mr *MockServiceMockRecorder) GetProcessedRanges(ctx, modelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProcessedRanges", reflect.TypeOf((*MockService)(nil).GetProcessedRanges), ctx, modelID)
}

// GetScheduledAdminDatabase mocks base method.
func (m *MockService) GetScheduledAdminDatabase() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduledAdminDatabase")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetScheduledAdminDatabase indicates an expected call of GetScheduledAdminDatabase.
func (mr *MockServiceMockRecorder) GetScheduledAdminDatabase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduledAdminDatabase", reflect.TypeOf((*MockService)(nil).GetScheduledAdminDatabase))
}

// GetScheduledAdminTable mocks base method.
func (m *MockService) GetScheduledAdminTable() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduledAdminTable")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetScheduledAdminTable indicates an expected call of GetScheduledAdminTable.
func (mr *MockServiceMockRecorder) GetScheduledAdminTable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduledAdminTable", reflect.TypeOf((*MockService)(nil).GetScheduledAdminTable))
}

// RecordCompletion mocks base method.
func (m *MockService) RecordCompletion(ctx context.Context, modelID string, position, interval uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordCompletion", ctx, modelID, position, interval)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordCompletion indicates an expected call of RecordCompletion.
func (mr *MockServiceMockRecorder) RecordCompletion(ctx, modelID, position, interval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordCompletion", reflect.TypeOf((*MockService)(nil).RecordCompletion), ctx, modelID, position, interval)
}

// RecordScheduledCompletion mocks base method.
func (m *MockService) RecordScheduledCompletion(ctx context.Context, modelID string, startDateTime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordScheduledCompletion", ctx, modelID, startDateTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordScheduledCompletion indicates an expected call of RecordScheduledCompletion.
func (mr *MockServiceMockRecorder) RecordScheduledCompletion(ctx, modelID, startDateTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordScheduledCompletion", reflect.TypeOf((*MockService)(nil).RecordScheduledCompletion), ctx, modelID, startDateTime)
}

// SetExternalBounds mocks base method.
func (m *MockService) SetExternalBounds(ctx context.Context, cache *admin.BoundsCache) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetExternalBounds", ctx, cache)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetExternalBounds indicates an expected call of SetExternalBounds.
func (mr *MockServiceMockRecorder) SetExternalBounds(ctx, cache any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExternalBounds", reflect.TypeOf((*MockService)(nil).SetExternalBounds), ctx, cache)
}
