/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DagRouteImport } from './routes/dag'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelIdRouteImport } from './routes/model/$id'

const DagRoute = DagRouteImport.update({
  id: '/dag',
  path: '/dag',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelIdRoute = ModelIdRouteImport.update({
  id: '/model/$id',
  path: '/model/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dag': typeof DagRoute
  '/model/$id': typeof ModelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dag': typeof DagRoute
  '/model/$id': typeof ModelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dag': typeof DagRoute
  '/model/$id': typeof ModelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dag' | '/model/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dag' | '/model/$id'
  id: '__root__' | '/' | '/dag' | '/model/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DagRoute: typeof DagRoute
  ModelIdRoute: typeof ModelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dag': {
      id: '/dag'
      path: '/dag'
      fullPath: '/dag'
      preLoaderRoute: typeof DagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model/$id': {
      id: '/model/$id'
      path: '/model/$id'
      fullPath: '/model/$id'
      preLoaderRoute: typeof ModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DagRoute: DagRoute,
  ModelIdRoute: ModelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
