// Code generated by MockGen. DO NOT EDIT.
// Source: validator.go
//
// Generated by this command:
//
//	mockgen -package mock -destination mock/validator.mock.go -source validator.go Validator
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/ethpandaops/cbt/pkg/models"
	validation "github.com/ethpandaops/cbt/pkg/validation"
	gomock "go.uber.org/mock/gomock"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
	isgomock struct{}
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// GetStartPosition mocks base method.
func (m *MockValidator) GetStartPosition(ctx context.Context, modelID string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStartPosition", ctx, modelID)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStartPosition indicates an expected call of GetStartPosition.
func (mr *MockValidatorMockRecorder) GetStartPosition(ctx, modelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStartPosition", reflect.TypeOf((*MockValidator)(nil).GetStartPosition), ctx, modelID)
}

// GetValidRange mocks base method.
func (m *MockValidator) GetValidRange(ctx context.Context, modelID string, semantics validation.RangeSemantics) (uint64, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidRange", ctx, modelID, semantics)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetValidRange indicates an expected call of GetValidRange.
func (mr *MockValidatorMockRecorder) GetValidRange(ctx, modelID, semantics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidRange", reflect.TypeOf((*MockValidator)(nil).GetValidRange), ctx, modelID, semantics)
}

// ValidateDependencies mocks base method.
func (m *MockValidator) ValidateDependencies(ctx context.Context, modelID string, position, interval uint64) (validation.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateDependencies", ctx, modelID, position, interval)
	ret0, _ := ret[0].(validation.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateDependencies indicates an expected call of ValidateDependencies.
func (mr *MockValidatorMockRecorder) ValidateDependencies(ctx, modelID, position, interval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateDependencies", reflect.TypeOf((*MockValidator)(nil).ValidateDependencies), ctx, modelID, position, interval)
}

// MockExternalValidator is a mock of ExternalValidator interface.
type MockExternalValidator struct {
	ctrl     *gomock.Controller
	recorder *MockExternalValidatorMockRecorder
	isgomock struct{}
}

// MockExternalValidatorMockRecorder is the mock recorder for MockExternalValidator.
type MockExternalValidatorMockRecorder struct {
	mock *MockExternalValidator
}

// NewMockExternalValidator creates a new mock instance.
func NewMockExternalValidator(ctrl *gomock.Controller) *MockExternalValidator {
	mock := &MockExternalValidator{ctrl: ctrl}
	mock.recorder = &MockExternalValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalValidator) EXPECT() *MockExternalValidatorMockRecorder {
	return m.recorder
}

// GetMinMax mocks base method.
func (m *MockExternalValidator) GetMinMax(ctx context.Context, model models.External) (uint64, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinMax", ctx, model)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMinMax indicates an expected call of GetMinMax.
func (mr *MockExternalValidatorMockRecorder) GetMinMax(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinMax", reflect.TypeOf((*MockExternalValidator)(nil).GetMinMax), ctx, model)
}
