// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ethpandaops/cbt/pkg/models/transformation (interfaces: Handler,IntervalHandler,ScheduleHandler,LimitsHandler,DependencyHandler,FillHandler)
//
// Generated by this command:
//
//	mockgen -package mock -destination mock/handler.mock.go github.com/ethpandaops/cbt/pkg/models/transformation Handler,IntervalHandler,ScheduleHandler,LimitsHandler,DependencyHandler,FillHandler
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	transformation "github.com/ethpandaops/cbt/pkg/models/transformation"
	gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// Config mocks base method.
func (m *MockHandler) Config() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(any)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockHandlerMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockHandler)(nil).Config))
}

// GetAdminTable mocks base method.
func (m *MockHandler) GetAdminTable() transformation.AdminTable {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminTable")
	ret0, _ := ret[0].(transformation.AdminTable)
	return ret0
}

// GetAdminTable indicates an expected call of GetAdminTable.
func (mr *MockHandlerMockRecorder) GetAdminTable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminTable", reflect.TypeOf((*MockHandler)(nil).GetAdminTable))
}

// GetTemplateVariables mocks base method.
func (m *MockHandler) GetTemplateVariables(ctx context.Context, taskInfo transformation.TaskInfo) map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateVariables", ctx, taskInfo)
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetTemplateVariables indicates an expected call of GetTemplateVariables.
func (mr *MockHandlerMockRecorder) GetTemplateVariables(ctx, taskInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateVariables", reflect.TypeOf((*MockHandler)(nil).GetTemplateVariables), ctx, taskInfo)
}

// RecordCompletion mocks base method.
func (m *MockHandler) RecordCompletion(ctx context.Context, adminService any, modelID string, taskInfo transformation.TaskInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordCompletion", ctx, adminService, modelID, taskInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordCompletion indicates an expected call of RecordCompletion.
func (mr *MockHandlerMockRecorder) RecordCompletion(ctx, adminService, modelID, taskInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordCompletion", reflect.TypeOf((*MockHandler)(nil).RecordCompletion), ctx, adminService, modelID, taskInfo)
}

// ShouldTrackPosition mocks base method.
func (m *MockHandler) ShouldTrackPosition() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldTrackPosition")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldTrackPosition indicates an expected call of ShouldTrackPosition.
func (mr *MockHandlerMockRecorder) ShouldTrackPosition() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldTrackPosition", reflect.TypeOf((*MockHandler)(nil).ShouldTrackPosition))
}

// Type mocks base method.
func (m *MockHandler) Type() transformation.Type {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(transformation.Type)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockHandlerMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockHandler)(nil).Type))
}

// Validate mocks base method.
func (m *MockHandler) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockHandlerMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockHandler)(nil).Validate))
}

// MockIntervalHandler is a mock of IntervalHandler interface.
type MockIntervalHandler struct {
	ctrl     *gomock.Controller
	recorder *MockIntervalHandlerMockRecorder
	isgomock struct{}
}

// MockIntervalHandlerMockRecorder is the mock recorder for MockIntervalHandler.
type MockIntervalHandlerMockRecorder struct {
	mock *MockIntervalHandler
}

// NewMockIntervalHandler creates a new mock instance.
func NewMockIntervalHandler(ctrl *gomock.Controller) *MockIntervalHandler {
	mock := &MockIntervalHandler{ctrl: ctrl}
	mock.recorder = &MockIntervalHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIntervalHandler) EXPECT() *MockIntervalHandlerMockRecorder {
	return m.recorder
}

// AllowGapSkipping mocks base method.
func (m *MockIntervalHandler) AllowGapSkipping() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllowGapSkipping")
	ret0, _ := ret[0].(bool)
	return ret0
}

// AllowGapSkipping indicates an expected call of AllowGapSkipping.
func (mr *MockIntervalHandlerMockRecorder) AllowGapSkipping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowGapSkipping", reflect.TypeOf((*MockIntervalHandler)(nil).AllowGapSkipping))
}

// AllowsPartialIntervals mocks base method.
func (m *MockIntervalHandler) AllowsPartialIntervals() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllowsPartialIntervals")
	ret0, _ := ret[0].(bool)
	return ret0
}

// AllowsPartialIntervals indicates an expected call of AllowsPartialIntervals.
func (mr *MockIntervalHandlerMockRecorder) AllowsPartialIntervals() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowsPartialIntervals", reflect.TypeOf((*MockIntervalHandler)(nil).AllowsPartialIntervals))
}

// GetMaxInterval mocks base method.
func (m *MockIntervalHandler) GetMaxInterval() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxInterval")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetMaxInterval indicates an expected call of GetMaxInterval.
func (mr *MockIntervalHandlerMockRecorder) GetMaxInterval() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxInterval", reflect.TypeOf((*MockIntervalHandler)(nil).GetMaxInterval))
}

// GetMinInterval mocks base method.
func (m *MockIntervalHandler) GetMinInterval() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinInterval")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetMinInterval indicates an expected call of GetMinInterval.
func (mr *MockIntervalHandlerMockRecorder) GetMinInterval() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinInterval", reflect.TypeOf((*MockIntervalHandler)(nil).GetMinInterval))
}

// MockScheduleHandler is a mock of ScheduleHandler interface.
type MockScheduleHandler struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleHandlerMockRecorder
	isgomock struct{}
}

// MockScheduleHandlerMockRecorder is the mock recorder for MockScheduleHandler.
type MockScheduleHandlerMockRecorder struct {
	mock *MockScheduleHandler
}

// NewMockScheduleHandler creates a new mock instance.
func NewMockScheduleHandler(ctrl *gomock.Controller) *MockScheduleHandler {
	mock := &MockScheduleHandler{ctrl: ctrl}
	mock.recorder = &MockScheduleHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleHandler) EXPECT() *MockScheduleHandlerMockRecorder {
	return m.recorder
}

// GetLimits mocks base method.
func (m *MockScheduleHandler) GetLimits() *transformation.Limits {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLimits")
	ret0, _ := ret[0].(*transformation.Limits)
	return ret0
}

// GetLimits indicates an expected call of GetLimits.
func (mr *MockScheduleHandlerMockRecorder) GetLimits() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLimits", reflect.TypeOf((*MockScheduleHandler)(nil).GetLimits))
}

// IsBackfillEnabled mocks base method.
func (m *MockScheduleHandler) IsBackfillEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBackfillEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBackfillEnabled indicates an expected call of IsBackfillEnabled.
func (mr *MockScheduleHandlerMockRecorder) IsBackfillEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBackfillEnabled", reflect.TypeOf((*MockScheduleHandler)(nil).IsBackfillEnabled))
}

// IsForwardFillEnabled mocks base method.
func (m *MockScheduleHandler) IsForwardFillEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsForwardFillEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsForwardFillEnabled indicates an expected call of IsForwardFillEnabled.
func (mr *MockScheduleHandlerMockRecorder) IsForwardFillEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsForwardFillEnabled", reflect.TypeOf((*MockScheduleHandler)(nil).IsForwardFillEnabled))
}

// MockLimitsHandler is a mock of LimitsHandler interface.
type MockLimitsHandler struct {
	ctrl     *gomock.Controller
	recorder *MockLimitsHandlerMockRecorder
	isgomock struct{}
}

// MockLimitsHandlerMockRecorder is the mock recorder for MockLimitsHandler.
type MockLimitsHandlerMockRecorder struct {
	mock *MockLimitsHandler
}

// NewMockLimitsHandler creates a new mock instance.
func NewMockLimitsHandler(ctrl *gomock.Controller) *MockLimitsHandler {
	mock := &MockLimitsHandler{ctrl: ctrl}
	mock.recorder = &MockLimitsHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLimitsHandler) EXPECT() *MockLimitsHandlerMockRecorder {
	return m.recorder
}

// GetLimits mocks base method.
func (m *MockLimitsHandler) GetLimits() *transformation.Limits {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLimits")
	ret0, _ := ret[0].(*transformation.Limits)
	return ret0
}

// GetLimits indicates an expected call of GetLimits.
func (mr *MockLimitsHandlerMockRecorder) GetLimits() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLimits", reflect.TypeOf((*MockLimitsHandler)(nil).GetLimits))
}

// MockDependencyHandler is a mock of DependencyHandler interface.
type MockDependencyHandler struct {
	ctrl     *gomock.Controller
	recorder *MockDependencyHandlerMockRecorder
	isgomock struct{}
}

// MockDependencyHandlerMockRecorder is the mock recorder for MockDependencyHandler.
type MockDependencyHandlerMockRecorder struct {
	mock *MockDependencyHandler
}

// NewMockDependencyHandler creates a new mock instance.
func NewMockDependencyHandler(ctrl *gomock.Controller) *MockDependencyHandler {
	mock := &MockDependencyHandler{ctrl: ctrl}
	mock.recorder = &MockDependencyHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDependencyHandler) EXPECT() *MockDependencyHandlerMockRecorder {
	return m.recorder
}

// GetDependencies mocks base method.
func (m *MockDependencyHandler) GetDependencies() []transformation.Dependency {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDependencies")
	ret0, _ := ret[0].([]transformation.Dependency)
	return ret0
}

// GetDependencies indicates an expected call of GetDependencies.
func (mr *MockDependencyHandlerMockRecorder) GetDependencies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDependencies", reflect.TypeOf((*MockDependencyHandler)(nil).GetDependencies))
}

// GetFlattenedDependencies mocks base method.
func (m *MockDependencyHandler) GetFlattenedDependencies() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlattenedDependencies")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetFlattenedDependencies indicates an expected call of GetFlattenedDependencies.
func (mr *MockDependencyHandlerMockRecorder) GetFlattenedDependencies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlattenedDependencies", reflect.TypeOf((*MockDependencyHandler)(nil).GetFlattenedDependencies))
}

// MockFillHandler is a mock of FillHandler interface.
type MockFillHandler struct {
	ctrl     *gomock.Controller
	recorder *MockFillHandlerMockRecorder
	isgomock struct{}
}

// MockFillHandlerMockRecorder is the mock recorder for MockFillHandler.
type MockFillHandlerMockRecorder struct {
	mock *MockFillHandler
}

// NewMockFillHandler creates a new mock instance.
func NewMockFillHandler(ctrl *gomock.Controller) *MockFillHandler {
	mock := &MockFillHandler{ctrl: ctrl}
	mock.recorder = &MockFillHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFillHandler) EXPECT() *MockFillHandlerMockRecorder {
	return m.recorder
}

// AllowGapSkipping mocks base method.
func (m *MockFillHandler) AllowGapSkipping() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllowGapSkipping")
	ret0, _ := ret[0].(bool)
	return ret0
}

// AllowGapSkipping indicates an expected call of AllowGapSkipping.
func (mr *MockFillHandlerMockRecorder) AllowGapSkipping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowGapSkipping", reflect.TypeOf((*MockFillHandler)(nil).AllowGapSkipping))
}

// GetFillBuffer mocks base method.
func (m *MockFillHandler) GetFillBuffer() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFillBuffer")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetFillBuffer indicates an expected call of GetFillBuffer.
func (mr *MockFillHandlerMockRecorder) GetFillBuffer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFillBuffer", reflect.TypeOf((*MockFillHandler)(nil).GetFillBuffer))
}

// GetFillDirection mocks base method.
func (m *MockFillHandler) GetFillDirection() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFillDirection")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetFillDirection indicates an expected call of GetFillDirection.
func (mr *MockFillHandlerMockRecorder) GetFillDirection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFillDirection", reflect.TypeOf((*MockFillHandler)(nil).GetFillDirection))
}
